In [ ]:
'''
Generate a 3x4 NumPy array with random integers between 1 and 50.   
a. Calculate and print the Mean, Median, and Standard Deviation of the array 
b. Print the Sum of all elements and the sum of each row. 
c. Reshape the 3x4 array into a 2x6 array and print it. 
'''
# Week 3, Code 1
# Nityant Agarwal, CC, 240953418

In [10]:
import numpy as np
import random as rd

In [11]:
l1 = []
for i in range(3):
    l2 = []
    for j in range(4):
        l2.append(rd.randint(1,50))
    l1.append(l2)
arr = np.array(l1)
print(arr)

[[47 43  8 22]
 [ 5 34 18  7]
 [38 36  3  4]]


In [26]:
print("mean = ",np.mean(arr))
print("median = ",np.median(arr))
print("standard deviation = ",np.std(arr))

mean =  22.083333333333332
median =  20.0
standard deviation =  16.002386974726267


In [29]:
print("Sum of all elemnts = ",arr.sum())
print("Sum of each row = ",arr.sum(axis = 1))

Sum of all elemnts =  265
Sum of each row =  [120  64  81]


In [17]:
print(np.reshape(arr,(2,6)))

[[47 43  8 22  5 34]
 [18  7 38 36  3  4]]
