In [ ]:
'''
Create two (3 * 3) matrices using NumPy and print it. Perform 
and print the results of the following linear algebra operations 
a. Matrix addition 
b. Matrix subtraction 
c. Matrix multiplication (element-wise and dot product) 
d. Transpose of a matrix 
e. Determinant and inverse (if applicable)
'''
# Week 3, Code 2
# Nityant Agarwal, CC, 240953418

In [2]:
import numpy as np

In [3]:
l = []
for j in range(3):
    l1 = []
    for k in range(3):
        l1.append(int(input("enter no: ")))
    l.append(l1)
a1 = np.array(l)    
print(a1)
l = []
for j in range(3):
    l1 = []
    for k in range(3):
        l1.append(int(input("enter no: ")))
    l.append(l1)
a2 = np.array(l)    
print(a2)

enter no: 1
enter no: 2
enter no: 3
enter no: 4
enter no: 5
enter no: 6
enter no: 7
enter no: 8
enter no: 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
enter no: 9
enter no: 8
enter no: 7
enter no: 6
enter no: 5
enter no: 4
enter no: 3
enter no: 2
enter no: 1
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [4]:
print("Matrix addition:\n",np.add(a1,a2))
print("Matrix Subtraction:\n",np.subtract(a1,a2))
print("Matrix Multiplication (element wise):\n",np.matmul(a1,a2))
print("Matrix Multiplication (dot product):\n",np.dot(a1,a2))
print("Transpose of a1:\n",np.transpose(a1))
print("Transpose of a2:\n",np.transpose(a2))
print("Determinant of a1:\n",int(np.linalg.det(a1)))
print("Determinant of a2:\n",int(np.linalg.det(a2)))
try:
    inv1 = np.linalg.inv(a1)
except np.linalg.LinAlgError:
    pass
else:
    print("Inverse of a1:\n",inv1)
try:
    inv2 = np.linalg.inv(a2)
except np.linalg.LinAlgError:
    pass
else:
    print("Inverse of a2:\n",inv2)


Matrix addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Matrix Subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Matrix Multiplication (element wise):
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Matrix Multiplication (dot product):
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Transpose of a1:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose of a2:
 [[9 6 3]
 [8 5 2]
 [7 4 1]]
Determinant of a1:
 0
Determinant of a2:
 0
Inverse of a1:
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
Inverse of a2:
 [[ 2.25179981e+15 -4.50359963e+15  2.25179981e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 2.25179981e+15 -4.50359963e+15  2.25179981e+15]]
